apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weg-case-study-cert
  namespace: istio-system
spec:
  secretName: weg-case-study-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: weg-case-study.ahmetbllgz.com
  dnsNames:
  - weg-case-study.ahmetbllgz.com