apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-restart-alert-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  pod-restart-dashboard.json: |
    {
      "annotations": {
        "list": [          
        {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "alert": {
            "conditions": [
              {
                "evaluator": {
                  "params": [0],
                  "type": "gt"
                },
                "operator": {
                  "type": "and"
                },
                "query": {
                  "params": ["A", "5m", "now"]
                },
                "reducer": {
                  "params": [],
                  "type": "avg"
                },
                "type": "query"
              }
            ],
            "executionErrorState": "alerting",
            "for": "5m",
            "frequency": "1m",
            "handler": 1,
            "name": "Pod Restart Alert",
            "noDataState": "no_data",
            "notifications": []
          },
          "datasource": "Prometheus",
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "targets": [
            {
              "expr": "increase(kube_pod_container_status_restarts_total{container=\"simple-web\"}[5m])",
              "format": "time_series",
              "interval": "",
              "legendFormat": "Pod Restarts",
              "refId": "A"
            }
          ],
          "title": "Pod Restart Alert Panel",
          "type": "graph"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 30,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-5m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Pod Restart Alert Dashboard",
      "uid": "pod-restart-alert"
    }
