global:
nodeSelector:
  cloud.google.com/gke-nodepool: "application-pool"

service:
  type: LoadBalancer
  loadBalancerIP: 34.77.72.173
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 8443
    - name: tcp
      port: 15443
      targetPort: 15443
